version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - NEO4J_URI=bolt://db:7687
    volumes:
      - sqlite_data:/app

  db:
    image: neo4j:latest
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=neo4j/superman
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:
  sqlite_data:
